compilation:
  cloud_properties: {}
  network: default
  reuse_compilation_vms: false
  workers: 4
director_uuid: dc4e8b29-2f3a-4051-8b66-39193791a57b
jobs:
- instances: 1
  name: memcached-node
  networks:
  - name: default
    static_ips:
    - 10.244.111.6
  persistent_disk: 65536
  properties:
    networks:
      apps: default
  resource_pool: default
  templates:
  - name: memcached-node
properties: {}
name: memcached
networks:
- name: default
  subnets:
  - cloud_properties: {}
    range: 10.244.111.4/30
    reserved:
    - 10.244.111.5
    static:
    - 10.244.111.6
  - cloud_properties: {}
    range: 10.244.111.8/30
    reserved:
    - 10.244.111.9
    static:
    - 10.244.111.10
  - cloud_properties: {}
    range: 10.244.111.12/30
    reserved:
    - 10.244.111.13
    static:
    - 10.244.111.14
  - cloud_properties: {}
    range: 10.244.111.16/30
    reserved:
    - 10.244.111.17
    static:
    - 10.244.111.18
  - cloud_properties: {}
    range: 10.244.111.20/30
    reserved:
    - 10.244.111.21
    static:
    - 10.244.111.22
  - cloud_properties: {}
    range: 10.244.111.24/30
    reserved:
    - 10.244.111.25
    static: []
  - cloud_properties: {}
    range: 10.244.111.28/30
    reserved:
    - 10.244.111.29
    static: []
  - cloud_properties: {}
    range: 10.244.111.32/30
    reserved:
    - 10.244.111.33
    static: []
  - cloud_properties: {}
    range: 10.244.111.36/30
    reserved:
    - 10.244.111.37
    static: []

releases:
- name: memcached
  version: latest
resource_pools:
- cloud_properties: {}
  name: default
  network: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 0
  canary_watch_time: 30000-240000
  max_in_flight: 1
  serial: true
  update_watch_time: 30000-240000

